### PR TITLE
[site:statistics] command fails when comment module is uninstalled. Fix #2744

### LINKED ISSUE #2744: [site:statistics] command fails when comment module is uninstalled.
I ran the site:statistics command on a site where the comment module was disabled/uninstalled and received the following error:
 [Drupal\Component\Plugin\Exception\PluginNotFoundException]
  The "comment" entity type does not exist.

Drupal                       8.1.8
Drupal Console version 1.0.0-rc1

### PR DESCRIPTION
**Pull request by daydiff**
fix failing command [site:statistics] when comment module is uninstalled

### CODE REVIEW

File: src/Command/Site/StatisticsCommand.php [hunk 1]
```diff
@@ -115,7 +116,12 @@ private function getNodeTypeCount($nodeType)
      */
     private function getCommentCount()
     {
-        $entityQuery = $this->entityQuery->get('comment')->count();
+        try {
+            $entityQuery = $this->entityQuery->get('comment')->count();
+        } catch (PluginNotFoundException $e) {
+            return 0;
```
Comment (daydiff) [inline src/Command/Site/StatisticsCommand.php]: But it is not the value CLI application returns, but the value of comments which is 0 when "Comment" module is not installed. Btw I agree, that it would be better to not catch exception but prevent it. I can replace catch block with something like this:

```php
if (!\Drupal::moduleHandler()->moduleExists('comment')) {
    return 0;
}
```
What do you think about such changes?

Comment (daydiff) [inline src/Command/Site/StatisticsCommand.php]: I replaced try-catch block so it is no exception now.

Comment (jmolivas) [inline src/Command/Site/StatisticsCommand.php]: My bad, but like this better value 0 instead of `PluginNotFoundException`

**Comment by jmolivas** [comment]
@daydiff Thanks for your contribution, your PR was merged. This will be included on the next release.
